[build]
  base = "Clover v2.9.1/Clover v2.9.1/codecanyon-25737452-clover-realtime-messaging-audio-video-conferencing-web-app-nodejs-react-webrtc-socketio/frontend"
  command = "npm install react-is --legacy-peer-deps && npm run build"
  publish = "Clover v2.9.1/Clover v2.9.1/codecanyon-25737452-clover-realtime-messaging-audio-video-conferencing-web-app-nodejs-react-webrtc-socketio/frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
